const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./src/app.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "ÂnimaPlay",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: process.env.APPLICATION_HOST,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [],
  securityDefinitions: {
    ApiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "x-access-token",
    },
  },
  definitions: {},
};

swaggerAutogen(outputFile, endpointsFiles, doc);
